#Este módulo surgiu da necessidade de armazenar mensagens de texto padronizadas, essas mensagens ocupavam muito espaço no código principal e estavam dificultando manutenções e atualizações.
#Então, a melhor alternativa foi transformá-las em um módulo que não interfere nesses procedimentos.



# Converte o texto em mono
def tornarSelecionavel(texto):
    selecionavel = f"<code>{texto}</code>"
    return selecionavel



#Dicionário para o armazenamento de mensagens de texto do telebot
msg = {
    'area_de_trabalho': 'Bom, esta é a sua área de trabalho📊📚\nCada botão te leva para um caminho diferente🛣🛤... utilize as instruções abaixo para se orientar:\n\n🔸Minhas turmas👩🏻‍🏫: Gerencie seus alunos os organizando em turmas.\n\n🔸Métodos avaliativos👨🏽‍🏫: Crie e administre seus métodos avaliativos para avaliar seus alunos de forma fácil e intuitiva.\n\n🔸Atividades programadas⏰: Um espacinho dedicado às suas anotações e lembretes!\n\n🔸Configurações⚙: Configure o ProfAux de acordo com as suas necessidades.\n\nClique em VOLTAR para retornar ao menu anterior🏃🏻‍♂🏃🏽‍♀',
    
    'relatorio_geral_canal_impossivel': f"""No momento é impossível realizar o envio de seu relatório❌\n\nVocê precisa estar com ao menos 1 canal de recebimento ativo para o envio ser realizado!\nFaça uma visita ao nosso menu de canais de recebimento para ativar um canal, estaremos lhe aguardando aqui para realizar o envio do seu relatório! 😊📊\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'relatorio_geral_turma_impossivel': f"""Infelizmente não foi possível gerar o seu relatório❌😔\n\nÉ necessário que você tenha cadastrado no mínimo 1 turma com alunos no ProfAux para que seja possível solicitar um relatório de médias.\nRetorne aqui após ter cadastrado a sua primeira turma, estarei lhe aguardando!😁✅\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'relatorio_geral_enviar': f"""Em instantes enviaremos o seu relatório para todos os canais de recebimento ativos!✅😉\n\nCaso queira receber seus relatórios em algum outro local, faça uma visita ao nosso menu de canais de recebimento 😊📊\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'relatorio_geral_enviado_pv': 'Aqui está o seu relatório! parabéns pelo bom trabalho, espero ter ajudado :)',
    'relatorio_geral_email': 'Olá! estou aqui para enviar o relatório que me foi solicitado agora pouco :)\n\nSegue o relatório com todas as médias de seus alunos:',
    'relatorio_geral_email_titulo': f'Relatório geral prof {"kaick"}',

    'reportar_erro': 'txt',
    'apoie_o_profaux': f"""Ficamos felizes em ver você participando do crescimento do ProfAux!\n\nPara apoiar, faça um pix utilizando a chave logo abaixo, envie um valor que não vá te fazer falta😊\n\nChave pix 🔑: {tornarSelecionavel('profauxproject@gmail.com')}\n\n\nA nossa aplicação foi desenvolvida com o objetivo de facilitar a organização de seus alunos, com métodos avaliativos simples e intuitivos📚😁... E nós não iremos parar por aqui, iremos trabalhar duro para que sua profissão seja cada vez mais fácil 📈.\n\nÉ o seu apoio o que torna o nosso projeto possível, contamos com sua ajuda para que possamos trazer cada vez mais novidades para simplificar a sua profissão que não é nada fácil😉✅\n\nDesde já, agradecemos por tudo!🙌🏽📊""",
            
    'meu_plano': f"""Informações sobre o seu plano ativo📊:\n\n🔸 Plano: {"checkAssinatura(call, 'call')"}\n🔸 Tempo restante: {"checkTimeAssinatura('call', call)"} dias\n\nObrigado por fazer parte do ProfAux!🎓\nA sua presença é de suma importância para o crescimento do projeto!👨🏽‍💻""",
    'assinar_opcoes': f"""Nunca é um gasto... Sempre será um investimento!🧠👨🏽‍🏫 Valorize seu tempo ⏳\nCom o ProfAux você não levará dias para avaliar todos os seus alunos... tudo será mais fácil daqui em diante📚📈\n\n🔸 Chegou a hora de escolher o seu plano! Temos disponíveis três opções:\n\n1 - Pacote básico\n✅Benefícios: 4 turmas👨🏽‍💻, 2 métodos avaliativos📖\n🔹Valor: {1},00R$\n\n2 - Pacote intermediário\n✅Benefícios: 8 turmas👨🏽‍💻, 4 métodos avaliativos📖\n🔹Valor: {1},00R$\n\n3 - Pacote completo\n✅Benefícios: 16 turmas👨🏽‍💻, 8 métodos avaliativos📖\n🔹Valor: {1},00R$\n\n✅🗃Todos os planos incluem: Relatório de médias, Metodologia de avaliação individual, Metodologia de avaliação geral, Análise aprofundada de médias, Espaço de anotações, entre outros...\n\n🔸 Observe que ao lado dos planos tem números, informe o número do plano que mais te interessa para continuar:""",
    'assinar_plano_escolhido': f"""Você selecionou o plano {"plano[0]"} e deverá pagar {"plano[1]"},00R$ na chave pix:\n\n🔸🔸🔸\n{"tornarSelecionavel(infos_pagamento[1])"}\n🔸🔸🔸\n\nDica: Pressione sobre a chave pix para copiar🙃\n\nOu pague clicando neste link🔗: {"infos_pagamento[0]"}\n\nO processo de pagamento é automático, ao efetuar o pagamento o seu acesso será liberado em instantes!📊\nCaso ocorra algum imprevisto ou dúvidas sobre o pagamento, entre em contato com o suporte clicando no botão abaixo👨🏽‍💻.\nTambém deixamos um botão para que você altere o plano escolhido antes da compra se necessário✅""",
    'assinar_opcao_indisponível': 'Só temos as opções 1,2 e 3... por favor, tente novamente da forma correta.',
    'assinar_novo_usuario': f'Olá {"call.from_user.first_name"}!\nNotei que você ainda não se cadastrou nos serviços do projeto Professor Auxiliar... já conhece o projeto? Deseja se cadastrar?\nUtilize os botões abaixo para prosseguir:',
    'assinatura_encerrada': """Nossa, seu plano já expirou?😔 foi bom enquanto durou...\n\nAgradecemos grandemente pelo apoio e confiança que você nos deu ao aceitar fazer parte do nosso projeto, queremos que você saiba que tudo isso foi feito graças a você!👩🏻‍🏫👨🏽‍🏫\nContinuaremos empenhados no crescimento do ProfAux📈, somos felizes em poder ouvir suas opiniões e dificuldades no ramo educacional, iremos trabalhar para que a vida dos educadores seja cada vez mais fácil! 📚📊\n\nQue tal renovar a sua assinatura?😁 Será um imenso prazer te ter conosco nessa jornada!\n\n🔸 Deixamos dois botões logo abaixo dessa mensagem para que você possa renovar sua assinatura e também ter a possibilidade de solicitar um relatório com as médias de seus alunos caso necessário❤""",

    'menu_novo_cliente': """Olá, tudo bem? boas vindas ao projeto ProfAux! 🎓\nVocê ainda avalia seus alunos manualmente? É cansativo né?😕\nE se eu te disser que nós temos a solução que você precisa?!😁✅\n\nAntes de tudo... você está pronto(a) para se despedir de trabalhos manuais e cálculos repetitivos?🤔\nNosso projeto intuitivo e personalizável permitirá que você gerencie suas turmas e avalie seus alunos de forma simples e eficaz, sendo até 10x mais rápido que métodos tradicionais! 👩🏻‍🏫👨🏽‍🏫\nAqui você terá vantagens e todas as ferramentas necessárias para simplificar sua vida no ramo educacional, poupando ao máximo o seu bem mais precioso... O seu tempo! ⏰📊\n\nDiga adeus às tarefas burocráticas e diga olá à produtividade📚⏳.\nO futuro da administração de alunos começa aqui!✍🏼✨""",

    'enviar_teste': f"""Informe o id do usuário para realizarmos o envio do TESTE:""",
    'receber_teste_cliente': f'Um administrador disponibilizou um teste gratuito para você✅.\n\nClique no botão abaixo para começar:',
    'teste_liberado': f'Tudo pronto! seu teste foi liberado!✅📚\n\nVocê tem muito trabalho pela frente... Correto??📚💻\nNão se preocupe, com a minha ajuda nós iremos terminar esta tarefa de forma simples e eficaz!✅\n\nUtilize os botões abaixo para navegar pelo menu:',
    'negar_teste': f'Infelizmente a sua solicitação de teste foi negada! 😔❌\n\nNo nosso sistema consta que você já utilizou seu período de testes em outra oportunidade.\n\nMas não se preocupe, os valores das assinaturas são bem acessíveis, considere eles como um investimento... Os benefícios que você terá no projeto compensam o valor investido⌛✅\nQualidade de ensino não tem preço, tem valor!🧠📈✨',

    'painel_adm': f'Bem vindo de volta {"call.from_user.first_name"}! este é seu painel de administrador:',
    'cadastro_manual': f"""Informe os dados abaixo:\n\n                    {"tornarSelecionavel('🔸🔸🔸🔸30🔸🔸🔸🔸')"}\n\n01 - Id_prof\n02 - Nome\n03 - Username\n04 - Vencimento\n05 - Plano\n06 - Id Pagamento\n07 - Valor\n\n🔸{"tornarSelecionavel('basico')"}🔸🔸{"tornarSelecionavel('intermediário')"}🔸🔸 {"tornarSelecionavel('completo')"}🔸""",
    'definir_valor_assinatura': f"""Informe os dados abaixo:\n\n                    {"tornarSelecionavel('🔸🔸🔸🔸🔸🔸🔸')"}\n\n01 - {"tornarSelecionavel('Básico')"}\n02 - {"tornarSelecionavel('Intermediário')"}\n03 - {"tornarSelecionavel('Completo')"}\n04 - TimeTest\n05 - planoTest""",
    'crud': f'O que vamos criar agora?🧩',
    'relatorio_clientes': 'Aqui está o seu relatório! parabéns pelo bom trabalho, espero ter ajudado :)',

    'verificando_pagamentos': f"""--------------------------------\n\nVerificando pagamentos... 📊✅💵💰\n\n--------------------------------""",
    'renovacao_de_plano': f"""Compra aprovada!✅\nRenovação de plano! 📈📈📈📈\n\nNome: 👩🏻‍🏫 {"tornarSelecionavel(infos_gerais[0][1])"} 👨🏽‍🏫\nUsername🪪: {"formatar(infos_gerais[0][2])"}\nId 🔎: {"tornarSelecionavel(formatar(infos_gerais[0][0]))"}\n\nValor 💶: {'infos_gerais[0][7]'},00R$\nPlano 📊: {'infos_gerais[0][6]'}\nId pagamento 🧩: {'tornarSelecionavel(infos_gerais[0][4])'}\n\nRenovações 🧠: {'int(formatar(renovacoes)) + 1'}\nCódigo indicação 📥: {'profaux23'}""",
    'compra_aprovada': f"""Compra aprovada!✅\n\nNome: 👩🏻‍🏫 {"tornarSelecionavel(infos_gerais[0][1])"} 👨🏽‍🏫\nUsername🪪: {"formatar(infos_gerais[0][2])"}\nId 🔎: {"tornarSelecionavel(formatar(infos_gerais[0][0]))"}\n\nValor 💶: {'infos_gerais[0][7]'},00R$\nPlano 📊: {'infos_gerais[0][6]'}\nId pagamento 🧩: {'tornarSelecionavel(infos_gerais[0][4])'}\n\nCódigo indicação 📥: {'profaux23'}""",

    'check_pay_manual': f"""Informe o id do pagamento para realizarmos a verificação:""",
    'check_pay_manual_aprovado': f'Deu tudo certo!✅\n\nBem vindo de volta {"call.from_user.first_name"}! este é seu painel de administrador:',

    'XXXXXverificando_horario': '--------------------------------\n\nVerificando horário... ⏳⏰\n\n--------------------------------',
    'XXXXXatualizando_assinaturas': '--------------------------------\n\nAtualizando assinaturas... ⏳⏰\n\n--------------------------------',

    'menu_principal': f'Olá {1}! \nVocê tem muito trabalho pela frente... Correto??📚💻\nNão se preocupe, com a minha ajuda nós iremos terminar esta tarefa de forma simples e eficaz!✅\n\nUtilize os botões abaixo para navegar pelo menu:',
    'menu_turmas': 'Este é o espaço onde você poderá criar, organizar e acessar suas turmas🧩\n\nUtilize o botão "Adicionar turma" para criar uma nova turma🎓.\n\nAo cadastrar uma turma, a mesma irá aparecer juntamente com os botões "Adicionar turma" e "voltar"✅\nEm seguida, basta clicar sobre a turma para acessá-la📚🎓\n\nAviso‼️: Toda assinatura possui um número máximo de turmas que podem ser cadastradas... por este motivo, o botão Adicionar turma ficará indisponível ao atingir este limite!\nVocê pode liberar espaço excluindo turmas, assim será possível cadastrar outras turmas fazendo uso do espaço liberado anteriormente✅\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀',
    'adicionar_turma': 'Por gentileza, informe o nome da turma que deseja cadastrar👩🏻‍🏫👨🏽‍💻:\n\nDicas de ouro🏆:\n\nOpte sempre por nomes fáceis de lembrar,que sejam simples e diferentes dos demais✅\nEvite nomes longos, pois os mesmos serão cortados caso excedam o limite de caracteres ❌\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀.',
    'adicionar_metodo': f"""Por gentileza, informe o nome de seu novo método avaliativo 📚:\n\nDica🏆: Use nomes simples e intuitivos, para que encontre seus métodos avaliativos com maior facilidade.\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    
    'turmaX': f'Aqui estão listados os nomes dos alunos da turma "{"(call).upper(checkNomeTurmaSelecionada)"}" e suas médias(lembrando que esses valores se alteram conforme os alunos são avaliados):\n\n{"listaOrientativaAlunos(call)"}\n\nOrientações:\n\nMédia mínima: {"checkGreen(call)"}\n\n🟢Acima da média\n🔴Abaixo da média\n🔵Não avaliado',

    'deletar_turma': f"""Tem certeza disso?😕\nTodos os registros da turma "{"checkNomeTurmaSelecionada(call).upper()"}" deixarão de existir... ao ser confirmada, a exclusão da turma será irreversível! ❌\n\n🔸Envie "{"tornarSelecionavel(senha)"}" para confirmar esta ação:""",
    'renomear_turma': f"""Vai renomear sua turma? Então me diga... Qual nome você escolheu? 📚:\n\nDica🏆: Use nomes simples e intuitivos, para que encontre suas turmas com maior facilidade.\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'adicionar_aluno_limite_atingido': f'Você não pode cadastrar mais de 35 alunos em uma única turma.\nPor este motivo,não será possível cadastrar o aluno que você deseja.\n\nClique no botão VOLTAR para retornar á turma 🧑🏻‍🎓 {"checkNomeTurmaSelecionada(call)"} 🧑🏽‍🎓',
    'perguntar_nome_aluno': f"""Por gentileza, informe o nome do aluno(a) que deseja adicionar à turma 🧑🏻‍🎓{"checkNomeTurmaSelecionada(call).upper()"}🧑🏽‍🎓:\n\nVocê ainda pode cadastrar💾: {"35 - checkNumAlunos(call)"} 🧑🏽‍🎓\n\nDicas de ouro🏆:\n\nQuer cadastrar vários alunos? Digite os nomes de todos eles em uma única mensagem, separando os nomes com vírgula.\n\n🔸 Exemplo:  André Torres, Maria Eduarda Gomes, Carlos Eduardo, Bruno da Silva...🧩\n\nNão se preocupe com ordem alfabética e letras maiúsculas, o ProfAux organiza tudo pra você!📚\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀.""",
    'adicionar_alunos_parcialmente': f'Você só pode cadastrar no máximo 35 alunos em cada turma, por este motivo só serão cadastrados os {"35 - checkNumAlunos(call)"} primeiros alunos informados, ok?',

    'remover_aluno': f"""Ambiente de exclusão de alunos ❌❌\n\n{"listaOrientativaAlunos(call)"}\n\nLogo acima estão listados todos os alunos presentes na turma 🧑🏾‍🎓{"checkNomeTurmaSelecionada(call).upper()"}🧑🏼‍🎓.\nObserve que tem números ao lado dos nomes dos alunos, informe o número correspondente ao aluno que você deseja remover🫥:\n\nEste é o ambiente de: remoção de alunos ❌""",
    'remover_aluno_numero_invalido': f'Aviso!\n\nVocê enviou um número inválido,não existe um aluno nesta turma com o indicador de número {"message.text"}.',
    'remover_aluno_caracteres_estranhos': f'Aviso!\n\nEnvie apenas o número indicador do aluno,não envie letras ou símbolos.',

    'renomear_aluno_selecao': f"""Este menu permitirá que você atualize os nomes de seus alunos 🧑🏾‍🎓\n\n{"listaOrientativaAlunos(call)"}\n\n\nErrou o nome do aluno? tudo bem... eu vou guardar segredo🤫, vamos corrigir!✅\n\nAcima estão listados todos os alunos presentes na turma 🧑🏾‍🎓{"checkNomeTurmaSelecionada(call).upper()"}🧑🏼‍🎓.\n🔸 Observe que tem números ao lado dos nomes dos alunos, encontre e informe o número correspondente ao aluno que você deseja alterar o nome🪪:""",
    'renomear_aluno': f"""Por gentileza, informe o novo nome para que seja possível realizar a alteração🪪\n\n🔸Obs: para melhorar a sua experiência, os nomes de todos os alunos são organizados em ordem alfabética! Então é normal que os nomes mudem de posição caso você atualize informações em suas turmas✅.\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",

    'metodos_avaliativos': f"""Este é o ambiente onde você poderá criar e gerenciar seus métodos avaliativos para avaliar seus alunos com maior facilidade👨🏽‍🏫✅\n\n🔸O principal objetivo dos métodos avaliativos é evitar que você perca tempo com tarefas maçantes, cálculos repetitivos, administração de atividades e também possibilitar que você tenha a melhor experiência possível, tendo a possibilidade de criar diversos tipos de avaliações automáticas e usá-las ao seu favor✅📊📚\n\n🔸Caso não tenha criado um método avaliativo, utilize o botão abaixo desta mensagem para essa finalidade.\n\n🔸Caso já tenha um método criado, clique sobre ele para acessá-lo.\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'metodo_avaliativo_vazio': """No momento você ainda não adicionou nenhuma avaliação neste método avaliativo...\n\nUtilize os botões abaixo para gerenciar seu método avaliativo💻📊:""",

    'atividades_programadas_vazio': f"""Esse é o espacinho onde você poderá deixar as suas anotações✍🏽✍🏻📝.\n\nDica de ouro 🏆: faça anotações simples e objetivas, assim você conseguirá anotar mais informações neste espaço... Sim, tem um limite para o tamanho das anotações, você não chegará nesse limite se for organizado(a) 😂😂\n\n🔸Suas anotações: 📄 📄 📄\n\nVocê ainda não fez anotações aqui.\n\n\n📄 📄 📄\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'atividades_programadas_escrito': f"""Esse é o espacinho onde você poderá deixar as suas anotações✍🏽✍🏻📝.\n\nDica de ouro 🏆: faça anotações simples e objetivas, assim você conseguirá anotar mais informações neste espaço... Sim, tem um limite para o tamanho das anotações, você não chegará nesse limite se for organizado(a) 😂😂\n\n🔸Suas anotações: 📄 📄 📄\n\n{"checkAtividadesProgramadas(call)"}\n\n\n📄 📄 📄\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'atividades_programadas_limite': 'Ops! A descrição enviada é muito longa, o limite de tamanho para a descrição é de 3300 caracteres.\n\nPor este motivo foi necessário remover parte da sua descrição, tente enviar uma descrição mais curta caso isso lhe incomode :)',
    'atividades_programadas_colinha': f"Precisa de uma mãozinha?🤚\nAQUI ESTÁ A SUA COLINHA 😁📄\nO texto é selecionável.. clique para copiar!📝\n\nSegue seu texto:\n\n📄 📄 📄\n\n{'tornarSelecionavel(descricao)'}\n\n\n📄 📄 📄\n\n\nClique em DISPENSAR COLINHA caso não queira fazer uso da mesma🫥",
    
    'deletar_metodo': f"""Tem certeza que quer fazer isso?😕\nTodos os dados deste método avaliativo deixarão de existir, inclusive os pontos que seus alunos receberam por meio de avaliações feitas com este método 📊 a exclusão deste método avaliativo é irreversível! ❌\n\n🔸Envie "{"tornarSelecionavel(senha)"}" para confirmar esta ação:""",
    'deletar_metodo_senha_incorreta': 'Aviso!\n\nVocê digitou a senha de forma incorreta,tente novamente clicando em EXCLUIR TURMA.\nNão se preocupe com os erros,as tentativas são ilimitadas.',
    'renomear_metodo': f"""Vai renomear seu método avaliativo? Então me diga... Qual nome você escolheu? 📚:\n\nDica🏆: Use nomes simples e intuitivos, para que encontre seus métodos avaliativos com maior facilidade.\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",

    'adicionar_questao': f"""Por gentileza, informe a resposta da questão que deseja adicionar✅:\n\nDicas de ouro🏆:\n\n🔸 Respostas longas irão dificultar o uso dos métodos avaliativos.\nPara uma melhor experiência, opte sempre por respostas simples e com poucos caracteres.\n\n🔸 Utilize respostas como: "A" , "B", "C", "D"... 1 , 2 , 3... "Fvfv" para alternativas de verdadeiro e falso... use sua criatividade, as possibilidades são infinitas.\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀.""",
    'adicionar_questao_limite': """Você não pode adicionar mais de 10 questões neste método avaliativo, caso você exclua uma questão... será possível cadastrar uma outra questão no lugar dela, lembrando que... todas as pontuações que partem do acerto desta questão serão removidas dos alunos que foram avaliados com a mesma.\n\nClique no botão abaixo para dispensar este aviso:""",
    'adicionar_questao_valor': f"""Para finalizar, informe quantos pontos esta questão valerá caso um aluno a responda corretamente📊:\n\n🔸 Números inteiros e decimais são aceitos, ou seja, você pode enviar apenas um número 5 ou 5,4 se quiser usar um valor mais exato... Ambas as formas estão corretas.\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",

    'remover_questao': f"""{"menuOrientativoQuestoes(call)"}\n\n\nPor gentileza, informe o número da questão que você deseja excluir📄❌:\n\n🔸Obs: indicamos fortemente que você evite excluir suas questões após as ter utilizado. Busque sempre registrar questões certeiras para que não haja a necessidade de editar ou excluir no futuro.\n\n🔸Ao excluir uma questão, a nota de acerto da mesma será removida dos resultados de todos os alunos, pois ela deixará de existir.\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'remover_questao_numero_invalido': "Envie apenas o número correspondente á questão que deseja excluir, caracteres diferentes não serão aceitos.",

    'alterar_descricao': f"""Qual será a descrição deste método avaliativo?📄\n\nDicas de ouro 🏆:\n\n🔸 Faça descrições curtas, para que você tenha a melhor experiência possível.\n\n🔸 O tamanho máximo para descrições é de 3200 caracteres, lembrando que... Quanto menor for a sua descrição, melhor será a visualização do seu método avaliativo.\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'alterar_descricao_limite': 'Ops! A descrição enviada é muito longa, o limite de tamanho para a descrição é de 3300 caracteres.\n\nPor este motivo foi necessário remover parte da sua descrição, tente enviar uma descrição mais curta :)',

    'campo_avaliativo': f"""Este é o espaço onde você poderá avaliar e checar o desempenho dos alunos presentes nesta turma📊📚\nLogo abaixo você tem duas opções:\n\n🔸Avaliar 📚:  clique neste botão para avaliar seus alunos.\n\n🔸Pontuações da turma 📊: clique para verificar as notas de seus alunos em uma avaliação específica.\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",

    'avaliar': f"""Aqui você poderá avaliar seus alunos👨🏽‍🏫👩🏼‍🏫\nUtilize os passos abaixo para se orientar:\n\n📕Turma sendo avaliada: {"checkNomeTurmaSelecionada(call).upper()"}\n📗Método avaliativo em uso: {"checkNomeMtdSelecionado(call).upper()"}\n\n🔸Caso não tenha um método avaliativo selecionado, clique em "Selecionar método" para escolher um.\n\nLogo em seguida:🔶Clique em "Avaliação individual" para avaliar 1 único aluno.\n\n🔶Ou clique em "Avaliação Geral" para avaliar vários alunos.\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",

    'avaliacao_sem_selecionar_mtd':"""Você não pode fazer uma avaliação sem antes ter selecionado um método avaliativo.\nUtilize o botão SELECIONAR MÉTODO para prosseguir\n\nClique no botão abaixo para dispensar este aviso:""",

    'avaliar_selecionar_aluno': f"""Que tal avaliar um de seus alunos de forma simples e rápida?📚:\n\n📗Método avaliativo em uso: {"checkNomeMtdSelecionado(call).upper()"}\n\n{"listaOrientativaAlunos(call)"}\n\n\nLogo acima estão listados todos os alunos presentes na turma 🧑🏾‍🎓{"checkNomeTurmaSelecionada(call).upper()"}🧑🏼‍🎓\n\n🔸 Observe que existem números ao lado dos nomes dos alunos, informe o número correspondente ao aluno que você deseja avaliar📚:\n\nTipo de avaliação: individual🧑🏾‍🎓""",
    'avaliar_alternativa_marcada': f"""Você está avaliando o aluno(a):📚 {"checkAluno(call).upper()"}\n\nQual alternativa foi marcada na questão número {"emojiColors[i]"} {"i"} {"emojiColors[i]"}?\n\nTurma em avaliação: {"nomeTurma.upper()"}\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'avaliacao_finalizada': f"""Avaliação finalizada👨🏽‍🏫👩🏼‍🏫!!\n\nClique em VOLTAR para verificar os resultados:""",
    'avaliar_indicador_invalido': f'Aviso!\n\nVocê enviou um valor inválido,não existe um aluno nesta turma com o indicador "{"lista[0]"}"... por este motivo iremos retornar ao início para que você tente novamente, ok?',

    'avaliacao_geral_selecionar_aluno': f"""Que tal avaliar vários de seus alunos de forma simples e rápida?📚:\n\n📗Método avaliativo em uso: {"checkNomeMtdSelecionado(call).upper()"}\n\n\n{"listaOrientativaAlunos(call)"}\n\n\nLogo acima estão listados todos os alunos presentes na turma 🧑🏾‍🎓{"checkNomeTurmaSelecionada(call).upper()"}🧑🏼‍🎓\n\nObserve que tem números ao lado dos nomes dos alunos, aqui nós iremos avaliar vários alunos.\n🔸 A partir de qual aluno você deseja avaliar? Envie o número correspondente ao aluno que está no ponto inicial📚:\n\nTipo de avaliação: geral👩🏻‍🎓👨🏼‍🎓🧑🏾‍🎓""",
    'avaliacao_finalizada': f"""Avaliação finalizada👨🏽‍🏫👩🏼‍🏫!!\n\nClique em VOLTAR para verificar os resultados:""",

    'avaliar_criar_metodo': 'Você ainda não possui métodos avaliativos cadastrados 😔.\nQue tal criar um método avaliativo agora mesmo?! clique no botão CRIAR MÉTODO para prosseguir\n\nObs: você terá que criar seus próximos métodos no menu de métodos avaliativos ok? estou apenas te guiando por um atalho hahaha\n\nRetorne aqui para avaliar seus alunos após ter criado seu método avaliativo🏃🏽‍♂🏃🏻‍♀',
    'avaliar_selecionar_metodo': f"""Qual dos métodos avaliativos abaixo você deseja utilizar para avaliar a turma {"checkNomeTurmaSelecionada(call).upper()"}?📚\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",

    'point_turma': f"""Ao acessar sua turma, foi possível visualizar as médias dos alunos presentes e gerenciar os mesmos📚\nAqui é um pouco diferente... Neste espaço você poderá checar as notas de seus alunos em avaliações específicas🔎📝\n\n🔸A turma aberta no momento é: {"checkNomeTurmaSelecionada(call).upper()"} 🧑🏽‍🎓\n\n🔸Todos os seus métodos avaliativos foram listados logo abaixo desta mensagem, selecione um deles para acompanhar o desempenho de sua turma no mesmo📚📊\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'view_points': f'Abaixo estão listadas as notas dos alunos da turma {"checkNomeTurmaSelecionada(call).upper()"} na avaliação {"checkNomeMtd(call, metodo).upper()"}:\n\n{"listaOrientativaPointsMtd(call, metodo)"}\n\nOrientações:\n\nValor da avaliação: {"green * 2"}\nPontuação média: {"green"}\n\n🟢Acima da média\n🔴Abaixo da média\n🔵Não avaliado',

    'configuracoes': f"""Este é o ambiente onde você poderá configurar o ProfAux do seu jeitinho!⚙📊\n\nOrientações💻:\n\n🔸Média verde 🔸 - clicando neste botão você poderá nos informar qual é a pontuação média para a aprovação de seus alunos, isso influenciará nos menus onde as notas de seus alunos são exibidas... Destacando com cores as notas positivas🟢 e negativas🔴.\n\n🔸Canais de recebimento 🔸 - te permite escolher onde você receberá seus relatórios, seja por email ou no pv 📚\n\n🔸Alterar apelido 🔸- nós naturalmente te chamamos pelo seu nome de usuário do telegram, mas te damos total liberdade para decidir como quer ser chamado pelo ProfAux 😁\n\n🔸Alterar divisor 🔸 - para calcular as médias de seus alunos, você divide as notas por qual valor? Utilize este botão para configurar o seu divisor✍🏽\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'alterar_media_green': f"""Média verde atual: {"checkGreen(call)"} 📚🟢\n\nQuer alterar sua média verde? responda a pergunta abaixo 😊:\n🟢 A partir de qual média um de seus alunos pode ser considerado aprovado?\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'green_alteracao_bem_sucedida': f"""Alteração bem sucedida!✅\nA sua média verde foi atualizada para {"novaMedia"} pontos!\n\n🔸Obs 🔸: ao atualizar sua média verde, os resultados de todos os seus alunos também são atualizados de acordo com a nova média!\nSendo assim, alunos com notas acima da média estarão destacados na cor verde🟢.\nJá os alunos abaixo da média terão ao lado de seus nomes o indicador vermelho🔴 para tornar tudo mais intuitivo!\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'green_valor_invalido': f'Aviso!\n\nVocê enviou um valor inválido, "{"message.text"}" não é um número! por este motivo nós iremos retornar ao início para que você tente novamente, ok?',
    'green_caractere_estranho':  'Aviso!\n\nVocê enviou um valor inválido, "{"message.text"}" não é um número! por este motivo nós iremos retornar ao início para que você tente novamente, ok?',
    
    'alterar_divisor': f"""Seu divisor atual é: {"checkDivisor(call)"} 📚🟢\n\nQuer alterar seu divisor? responda a pergunta abaixo 😊:\n\n🟢 Após determinado período (bimestre,semestre...) todas as notas dos alunos são somadas e no fim divididas por um número específico para resultar na média final dos alunos...\n🔸 Você divide as notas de seus alunos por qual valor para descobrir a média dos mesmos?\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'alterar_divisor_bem_sucedido': f"""Alteração bem sucedida!✅\nO seu divisor agora é {"novoDivisor"}!\n\n🔸Obs 🔸: ao alterar seu divisor, os resultados de todos os seus alunos também serão atualizados de acordo com as novas médias que serão obtidas com este novo divisor!\nOu seja... você não precisa se preocupar em fazer cálculos de média, eu já fiz tudo para você e atualizarei as médias sempre que necessário 😁!\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'alterar_divisor_valor_invalido':  f'Aviso!\n\nVocê enviou um valor inválido, "{"message.text"}" não é um número! por este motivo nós iremos retornar ao início para que você tente novamente, ok?',
    
    'alterar_apelido': f"""Nós normalmente te chamamos pelo nome de usuário que você define ao se cadastrar no telegram 💻\nCaso não se sinta confortável com este nome... Permitiremos que você o altere em nosso sistema!✅\n\n🔸Envie seu novo nome para que possamos te chamar da forma que você achar melhor!😁📚\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'alterar_apelido_finalizado': f"""Ok,agora irei te chamar de prof {"formatarNome(novoApelido)"}😄📚!\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",

    'adicionar_email': f"""Informe seu email para realizar o cadastro:\n\n🔸 É recomendado que você envie seu email da seguinte forma:  meuemail@gmail.com 📩\n\n🔸 Certifique-se de digitar seu email corretamente para que não ocorram enganos.\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'adicionar_email_finalizado': f"""Parabéns, o email {"email"} foi adicionado com sucesso!✅\n\n🔸Importante 🔸: ao retornar, você deverá clicar no botão CONFIRMAR EMAIL para finalizar o cadastro do mesmo.\nAo concluir este passo, você poderá utilizar seu email para receber seus relatórios bimestrais e também os futuros avisos do projeto ProfAux 📚😌\nNão se preocupe, a confirmação é um processo bem simples que foi feito pensando em sua segurança! 😊\n\n🔸Se você já possuía um email cadastrado anteriormente, saiba que este email foi desconectado dos serviços do ProfAux e substituído pelo email {"email"} 📩\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    
    'enviar_confirmacao_email': f'Olá! agora pouco você cadastrou o seu email no projeto professor auxiliar, então estou aqui para lhe enviar seu código de confirmação :)\n\nEste é o seu código: {"chave_email"}\n\nEntenda a importância de confirmar seu email:\n\n-Para que possamos enviar relatórios bimestrais ou avisos, é importante que tenhamos a certeza de que este email é seu, enganos não podem ocorrer.\n-Recuperação de conta em casos específicos.\n-Receber novidades sobre o projeto ProfAux :)\n\nObrigado por fazer parte deste projeto, é um prazer lhe atender!',
    'email_incorreto_negar': f'Aviso!\n\nVocê não enviou um email, por este motivo iremos retornar ao início para que você tente novamente, ok?',

    'canais_recebimento': f"""Por este menu você poderá configurar e atualizar informações sobre seus canais de recebimento! ou seja... receba seus relatórios onde você desejar! 📲\n\nOrientações:\n\n🔸Meus canais 🔸 - é onde você poderá cadastrar e confirmar seus canais de recebimento.\n\n🔸Recebimento 🔸 - Nessa opção você poderá decidir em quais canais de recebimento você deseja receber seus relatórios e avisos.\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
    'meus_canais': f'Olá, estes são os seus canais de recebimento cadastrados:\n\n{"ball"}Email: nenhum email cadastrado\nCanal: Canal de recebimento - PROFAUX\n\nQue tal cadastrar um email para poder receber seus relatórios bimestrais? é bem rápido e seguro! apenas 2 passos curtos... vapt vupt!\n\nClique em VOLTAR para retornar ao menu anterior.',
    'email_finalizar_cadastro': f"""Hora de finalizar seu cadastro!💻✅\nNós te enviamos uma mensagem em seu email, nela está presente a sua senha de confirmação 🔐📬\nPor gentileza, acesse este email e informe a senha de 4 dígitos para que seja possível finalizar o cadastro de seu email📩\n\n🔸 Certifique-se de enviar a senha corretamente para que não seja necessário repetir este processo.\n\n\nClique em VOLTAR para retornar ao menu anterior🏃🏽‍♂🏃🏻‍♀""",
                
    'confirmar_email': f'O seu email já foi confirmado e está em condições de uso, recomendo que você dê uma olhadinha no menu RECEBIMENTO... você irá encontrar ele no menu CANAIS DE RECEBIMENTO :)',
    'configurar_canais':f"""Utilize os botões abaixo para definir onde você deseja receber seus relatórios bimestrais e avisos⚙💻\n\n{"menuOrientativoCanaisRecebimento(call)"}\n\nOrientações:\n\n🔸 Logo acima existem as opções "Email" e "PV (privado)", observe que ao lado deles existem indicadores coloridos... Sendo o indicador 🟢 para RECEBER e o indicador 🔴 para NÃO RECEBER arquivos no canal correspondente, utilize os botões abaixo para configurar:""",
    'att_channel': 'Aviso:\n\nÉ necessário que você complete o cadastro do seu email no ProfAux para que seja possível receber arquivos nele!\nPor gentileza, vá ao menu MEUS CANAIS e finalize o cadastro do seu email\n\nAssim que concluir... retorne aqui para ativar o recebimento por email, estarei te aguardando :)',

}

#As classes acessam este menu quando é necessário exibir um painel com botões na tela do usuário
submenus = {
    'mp': ['Área de trabalho', 'Relatório geral', 'Reportar erro', 'Apoie o projeto', 'Meu plano'],
    'at': ['Minhas turmas', 'Métodos avaliativos', 'Anotações', 'Configurações'],
    'mt': ['turma1', 'turma2', 'turma3', 'turma4', 'turma5', 'turma6', 'turma7', 'turma8',
               'turma9', 'turma10', 'turma11', 'turma12', 'turma13', 'turma14', 'turma15',
               'turma16', 'Adicionar turma', 'Adicionar aluno', 'Remover aluno', 'Renomear aluno', 'Campo avaliativo', 'Excluir turma', 'Renomear turma'],
    'ca': ['Avaliar', 'Pontuações da turma', 'Avaliação individual', 'Avaliação geral', 'Selecionar método', 'Select_mtd1', 'Select_mtd2', 'Select_mtd3', 'Select_mtd4',
                'Select_mtd5', 'Select_mtd6', 'Select_mtd7', 'Select_mtd8', 'view_mtd1', 'view_mtd2', 'view_mtd3', 'view_mtd4',
                'view_mtd5', 'view_mtd6', 'view_mtd7', 'view_mtd8'],
    'ma': ['mtd1', 'mtd2', 'mtd3', 'mtd4',
                'mtd5', 'mtd6', 'mtd7', 'mtd8', 'Adicionar método', 'Adicionar questão', 'Remover questão', 'Renomear método', 'Alterar descrição', 'Excluir método'],
    'cf':['Média verde', 'Canais de recebimento', 'Alterar apelido', 'Alterar divisor', 'Meus canais', 'Recebimento', 'Adicionar email', 'Confirmar email', 'Receber', 'attemail', 'attpv', 'attcanal'],
    'sf': ['Dispensar aviso', 'Editar anotações', 'Ocultar texto', 'Exibir texto']
}
